<script type="text/javascript">
    $(document).ready(function() {
        $('#vehicle3').click(function() {
            if ($(this).is(':checked')) {
                $("[data-target='#modal-check']").click();
                if ($("#stat").val() == 'RELEASED')
                    $("#checkValue").show();//hide
            } else {
                $("#checkValue").show();
            }
        });
    });
</script>
<script type="text/javascript">
    $(document).ready(function() {
        $("#checkValue").show();//hide
        $("#modalhide").hide();
        $("#modalhide2").hide();
        $('#mypolicy2monitoring2').hide();
        $(".fileUpload ").show();//show
        $('input[type="file"]').change(function(e) {
            var fileName = e.target.files[0].name;
            $('.uploadimage').html(fileName);
            $('.imgname').val(fileName);
            $('#mypolicy2monitoring2 tbody').empty();
            var removeLink = "  <a class='removeFile' href=\"#\">Remove</a>";
            $('.uploadimage').append(removeLink);
        });
        $(this).on("click", ".removeFile", function(e) {
            e.preventDefault();
            $('.imgname').val('');
            $('#mypolicy2monitoring2 tbody').empty();
            $('.removeFile').parent().empty();
            // $("#file-upload").val(null);
        });
        //start the upload
        $("#upload-form2").submit(function(e) {
            e.preventDefault();

            // REQUIRED
            $(".padtype").remove();
            $(".padtypeinfo_check_error").remove();
            $(".padtype_info_check_success").remove();

            $(".intermediary").remove();
            $(".intermediary_check_error").remove();
            $(".intermediary_info_check_success").remove();


            errornumber = 0;

            if ($('#padtype').val() == "") {
                $('#padtype').css('border-color', '#F44336');
                $("#padtype").after(
                    "<div class='padtype v-error-msg' style='opacity:0.7;color:#F44336;'>Pad Type is Required</div>"
                );
                $('#padtype').after(
                    '<i class="fa fa-times-circle padtypeinfo_check_error fa-2x" aria-hidden="true" style=" float: right;top:-45px; position: relative;left:-10px !important;color: #F44336;size:20px;"></i>'
                );
                errornumber = 1;
            } else {
                $('#padtype').after(
                    '<i class="fa fa-check-circle padtype_info_check_success fa-2x" aria-hidden="true" style=" float: right;top:-45px; position: relative;left:-10px !important;color: #4BB543;size:20px;"></i>'
                );
                $('#padtype').css('border-color', '#4BB543');
            }
            if ($('#intermediary').val() == "") {
                $('#intermediary').css('border-color', '#F44336');
                $("#intermediary").after(
                    "<div class='intermediary v-error-msg' style='opacity:0.7;color:#F44336;'>Intermediary is Required</div>"
                );
                $('#intermediary').after(
                    '<i class="fa fa-times-circle intermediary_check_error fa-2x" aria-hidden="true" style=" float: right;top:-45px; position: relative;left:-10px !important;color: #F44336;size:20px;"></i>'
                );
                errornumber = 1;
            } else {
                $('#intermediary').after(
                    '<i class="fa fa-check-circle intermediary_info_check_success fa-2x" aria-hidden="true" style=" float: right;top:-45px; position: relative;left:-10px !important;color: #4BB543;size:20px;"></i>'
                );
                $('#intermediary').css('border-color', '#4BB543');
            }

            if (errornumber == 1) {
                return false;
            } else {
                // Show loading screen
                $('#loading-screen').removeClass('hidden');
            }

            // Show loading screen
            $('#loading-screen').removeClass('hidden');
            var reqpad = jQuery('#reqaddpads').val();
            jQuery('#padrequest').val(reqpad);
            var _token = jQuery('input[name="_token"]').val(); //generated by csrf field
            var formData = new FormData(this);
            formData.append('_token', _token);
            $.ajax({
                url: "{{ route('import') }}",
                method: "POST",
                data: formData,

                type: "POST",
                cache: false,
                contentType: false,
                processData: false,
                success: function(data) {
                    if (data.padrange) {
                        $('#padragerequire').text(data.padrange);
                        $("[data-target='#modal_warning']").click();
                    }
                    // Hide loading screen
                    $('#loading-screen').addClass('hidden')
                    if (data.Error && data.Error === 'Check your Policy Format') {
                        alert('No record found!');
                    } else {
                        if (data == 'sentrequest') {
                            $('.stat').val('PENDING')
                            $("[data-target='#modal_success']").click();
                            $('#manualpadtype').prop('checked', false);
                            $('#reqaddpads').val('')
                        } else {
                            $('#mypolicy2monitoring2 tbody').empty();

                            if (data.expired) {
                                let modalBody = "";
                                modalBody += "";
                                data.expired.forEach(function(id) {

                                    if (id !== "" && id !== null) {
                                        modalBody += "Series " + id +
                                            " is Expired<br>";
                                    }
                                });
                                modalBody += "";
                                $("#modalBody").html(modalBody);
                                $('#mypolicy2monitoring2').hide();
                                // $("body").append(data);
                                $("[data-target='#modal-exist']").click();

                            }



                            if (!data.nonExistentIds) {
                                $('#mypolicy2monitoring2').show();
                                $.each(data, function(key, value) {
                                    var tr = $("<tr />")
                                    $.each(value, function(k, v) {
                                        tr.append(
                                            $("<td />", {
                                                html: v
                                            })[0].outerHTML
                                        );
                                        $("table #ajaxresponse").append(tr)
                                    })
                                    $('#ajaxresponse').show();
                                })
                            } else {
                                if (data.nonExistentIds) {
                                    let modalBody = "";
                                    modalBody += "";
                                    data.nonExistentIds.forEach(function(id) {
                                        if (id !== "" && id !== null) {
                                            modalBody += "Series " + id +
                                                " is not assigned to the producer<br>";
                                        }
                                    });
                                    modalBody += "";
                                    $("#modalBody").html(modalBody);
                                    $("body").append(data);
                                    $("[data-target='#modal-exist']").click();

                                }
                            }

                            if (data.duplicate) {
                                let modalBody = "";
                                modalBody += "";
                                data.duplicate.forEach(function(id) {
                                    if (id !== "" && id !== null) {
                                        modalBody += "Series " + id +
                                            " is Duplicate<br>";
                                    }
                                });
                                modalBody += "";
                                $("#modalBody").html(modalBody);
                                $('#mypolicy2monitoring2').hide();
                                // $("body").append(data);
                                $("[data-target='#modal-exist']").click();

                            }

                        }
                    }
                    $('.removeFile').parent().empty();


                },
                error: function(data) {
                    // Hide loading screen
                    $('#loading-screen').addClass('hidden');

                    // Parse the error message as a JSON object
                    var errors = JSON.parse(data.responseText);

                    // Loop through the errors and display a message for each one
                    for (var i = 0; i < errors.length; i++) {
                        var error = errors[i];
                        var message = "An error occurred while uploading the file:\n";
                        message += "PAD Type: " + error.padtype + "\n";
                        message += "PAD Range: " + error.padrange + "\n";
                        message += "Intermediary: " + error.intermediary + "\n";
                        message += "Date Uploaded: " + error.dateupload + "\n";
                        message += "Record Count: " + error.recordcount + "\n";
                        message += "Uploader: " + error.uploader + "\n";

                        // Display the error message to the user
                        alert(message);
                    }
                },

            });
        });

    });
</script>
<script>
    function triggerOnChange() {

        $('#intermediaryname').val($("#intermediary option:selected").text());
        $('#intermediarynum').val($("#intermediary").val());
        $('#file-upload').val('');
        $('#mypolicy2monitoring2').hide();
        $('#ajaxresponse tr:last').remove();
        var _token = jQuery('input[name="token"]').val();
        var intermediary = jQuery('#intermediary').val();
        var padtypeval = jQuery('#padtype').val();

        $.ajax({
            type: "GET",
            url: "{{ route('checkApprove') }}",
            data: {
                intermediary: intermediary,
                padtypeval: padtypeval,
                _token: _token
            },
            success: function(data) {
                // Check the condition
                //    var trimintermediary = data.trim().toLowerCase();
                if (data === 'padtype') {
                    $('.stat').val("");
                    $("[data-target='#modal_padtype']").click();
                    $('#vehicle3').prop('checked', false);
                } else {
                    $('.stat').val(data);
                    if (data === "RELEASED") {
                        $("#checkValue").show();
                        $(".fileUpload ").show();
                    } else {
                        $("#checkValue").show();//hide
                    }
                    if (data === "PENDING" || data === "APPROVED") {
                        // $('#uploadBtn').hide();
                        // $('#modal_alert_button').prop("disabled", false);
                        // $("[data-target='#modal_alert']").click();
                        // $('#modal_alert_button').prop("disabled", true);
                    } else {
                        $('#uploadBtn').show();
                        $('#modal_alert_button').prop("disabled", true);
                    }
                    //  if (trimintermediary === "no request") {
                    //     alert('Change');
                    //     $('#modal_alert_button').prop("disabled", false);
                    // }

                }


            }
        });
    }

    $(document).on("change", "#intermediary, #padtype", function() {
        triggerOnChange();
    });
</script>
