<div class="modal fade" id="showTableDetails" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl" style="width: 100%;">
        <div class="modal-content">
        <div class="modal-header" style="height:50px !important;margin-bottom: 40px !important;">
          <h1  class="modal-title" id="exampleModalLabel" style="color:white;">Details</h1>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>

        </div>
        <div class="modal-body" style='background-color:white'>
          <table class="table">
              <thead>
                  <tr>
                      <th>Trans ID</th>
                      <th>Assured</th>
                      <th>Invoice Number</th>
                      <th>Policy Number</th>
                      <th>Policy Issue Date</th>
                      <th>Status</th>
                      <th>Date Uploaded</th>
                  </tr>
              </thead>
              <tbody id="details">
              </tbody>
          </table>
        </div>
        <input type="hidden" name="ownerid" value='' id='ownerid' >
        <input type="hidden" name="intermediaryno" value='' id='intermediaryno' >
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>


<script>
  $(document).on('click', '.motorClaim', function() {

   var id = $(this).data('id');

   var id2 = $(this).data('id2');
   var intermediaryno=$('#intermediaryno').val(id2);
   var ownerid =  $('#ownerid').val(id);
   $.ajax({
            type: 'GET',
            url:'{{url('/')}}' + '/get-quote/manual-generate-list-table/'+id+'/intermediaryid/'+id2,
            success: function(data) {
                var details = '';

                $.each(data, function(id, columns) {
                    console.log(columns);
                    var createddate = columns['created_at'] !== undefined ? columns['created_at'] : '';
                    var issuedate =columns['issuedate']=== '1970-01-01' ? '' : columns['issuedate'];
                    var invoice =  (columns['invoice_no'] !== undefined && columns['invoice_no'] !== null) ? columns['invoice_no'] : '';
                    var policynum = (columns['policy_id'] !== undefined && columns['policy_id'] !== null) ? columns['policy_id'] : '';
                    var status = (columns['status'] !== undefined && columns['status'] !== null) ? columns['status'] : '';
                    details += '<tr><td>' + columns['adminpolicyno'] + '</td><td>' + columns['assuredname'] + '</td><td>' + invoice + '</td><td>' + policynum + '</td><td>' + issuedate + '</td><td>' + status + '</td><td>' +  createddate + '</td></tr>';
                });
                $('#details').html(details);
            }
        });
});
    </script>
<script>
    $('#search-form').submit(function(event) {
    event.preventDefault();
    var searchstart = $('#start').val();
    var searchend = $('#end').val();
    var intermediaryNo = $('#intermediary').val();
    var status = $('#status').val();
     var _token = jQuery('input[name="_token"]').val(); //generated by csrf field

    $.ajax({
        url: "{{ route('generateFilter') }}",
        method: 'POST',
        data: { searchstart: searchstart,
                searchend: searchend,
                intermediaryNo: intermediaryNo,
                status:status,
                _token: _token },
        success: function(response) {

                    // $('#myTableMonitor').hide();
                    // $('#myTableMonitor2').show();
                    $('#display_all_success tr:last').remove();
                    $('#myTableMonitor tbody').empty();
                    var rows = '';
                    $.each(response, function(index, data) {
                        console.log(data);
                        if( data.padtype =='PC'){
                            var pad_name_type = 'Private Car';
                        }else if(data.padtype =='CV'){
                            var pad_name_type = 'Commercial Vehicle';
                        }else if(data.padtype =='MCY'){
                            var pad_name_type = 'Motorcycle';
                        }else if(data.padtype =='ENDT'){
                            var pad_name_type = 'Endorsement';
                        }else{
                            var pad_name_type = 'CTPL';
                        }

                    rows += '<tr>';
                    rows += '<td>' + data.padrange + '</td>';
                    rows += '<td>' + pad_name_type + '</td>';
                    rows += '<td>' + data.intermediaryname + '</td>';
                    rows += '<td>' +  data.dateupload.split(' ')[0]  + '</td>';
                    rows += '<td>' +(data.used_doc !== null ? data.used_doc : '')+ '</td>';
                    rows += '<td><a href="#" data-toggle="modal" data-target="#showTableDetails" class="motorClaim" data-id='+data.intermediarycount+'  data-id2="' + data.intermediary + '" style="text-decoration: underline;color:#008080"> View</a></td>';

                    rows += '</tr>';


                    });
                    $('#myTableMonitor tbody').html(rows);
                // Clear existing rows in the table body


        }
    });
});
    </script>
